### PR TITLE
Adds possibility for currencies

### PR DESCRIPTION
**Pull request by ramonstohr**
Hi there, hope thats someway ok ;) 
I usually use WinForms  at work :)

Greetings from switzerland

### CODE REVIEW

**Comment by stvn1337** [comment]
Very nice work! Thanks for contributing. Greetings from the states.

**Comment by ramonstohr** [comment]
hi there, no problem. If theres more to do just ask ;)

**Comment by stvn1337** [comment]
Next on the list is to add payee and payer name to the receipt and make the receipt look better.  Take your pick  :)

**Comment by ramonstohr** [comment]
hi there, ok :)
im going to create that.
is it ok if i implement some viewmodels & a bit of a refactoring the code?

thanks in advance

**Comment by stvn1337** [comment]
Absolutely, go right ahead!

**Pull request merged**
